project_id = "mwkggtbuibwqmcwcppnm"

[functions.send-contact-email]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-reset-otp]
verify_jwt = false

[functions.analyze-transcript]
verify_jwt = false